name: Workflow for S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: AKIAVFGRN34STUF2JVCI
      AWS_SECRET_ACCESS_KEY: 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
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn bundle:ios

      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: build
          bucket: sd4688-miniapps
          bucket-region: us-east-1
          dist-id: E1RUL4EIU7OTS9
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'