name: Workflow for S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    environment: AWS
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # steps:
    #   - uses: actions/checkout@v3

    #   - name: Install dependencies
    #     run: yarn

    #   - name: Build
    #     run: yarn bundle:ios

    #   - name: Deploy
    #     uses: reggionick/s3-deploy@v4
    #     with:
    #       folder: build/outputs/ios/remotes
    #       bucket: ${{ secrets.S3_BUCKET }}
    #       bucket-region: ${{ secrets.S3_BUCKET_REGION }}
    #       dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
    #       invalidation: /
    #       delete-removed: true
    #       no-cache: true
    #       private: true
    #       files-to-include: '{.*/**,**}'
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install dependencies
          run: yarn
        - name: Build
          run: yarn bundle:ios
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.S3_BUCKET_REGION }}
        - name: Deploy
          uses: jonelantha/gatsby-s3-action@v3
          with:
            dest-s3-bucket: ${{ secrets.S3_BUCKET }}
            cloudfront-id-to-invalidate: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            dest-s3-path: news